{% set version = "2.6.1" %}

package:
  name: python-infomap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/infomap/infomap-{{ version }}.tar.gz
  sha256: 5fb76e8845b41c80e8a1bc522d518e5b233a1c893db11ebc6a5b3dc68ada711b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - infomap = infomap:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  imports:
    - infomap
  commands:
    - pip check
    - infomap --version
    - infomap --help

about:
  home: https://www.mapequation.org/infomap
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: Infomap network clustering algorithm
  doc_url: https://mapequation.github.io/infomap/python/

extra:
  recipe-maintainers:
    - TnTo
    - bollwyvl
