{% set name = "python-infomap" %}
{% set pyname = "infomap" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pyname[0] }}/{{ pyname }}/{{ pyname }}-{{ version }}.tar.gz
  sha256: 1310794b1834bfee66b3cb523880ef2bd349cd3f1446256d60b7b62c97c07b23

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - infomap

about:
  home: https://www.mapequation.org/infomap
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE_AGPLv3.txt
  summary: Infomap is a network clustering algorithm based on the Map equation. Python package.
  doc_url: https://mapequation.github.io/infomap/python/

extra:
  recipe-maintainers:
    - TnTo
