{% set pytest_args = "--cov-fail-under=59 -k \"not (multilevel_modules_on_physical or multilevel_modules_states)\"" %}
{% set pytest_args = '--cov-fail-under=59 -k "not (multilevel_modules_on_physical or multilevel_modules_states)"' %}
{% set version = "2.7.0" %}

package:
  name: python-infomap
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/i/infomap/infomap-{{ version }}.tar.gz
    sha256: 01321ab3022ad4ce8b7b5febad520f5a3b37b9ea51275be65216d2914c5d57d8
  - folder: src
    url: https://github.com/mapequation/infomap/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 51d7e4c3552e6973c4bfb4d00637612eafa9f72c0cfd12ec3725570d62a8ba02

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - infomap = infomap:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - llvm-openmp     # [osx]
    - libgomp         # [linux]
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - src/test
    - src/examples/networks
  requires:
    - pip
    - pytest-cov
  imports:
    - infomap
  commands:
    - pip check
    - infomap --version
    - infomap --help
    - python -c "__import__('shutil').copytree('src/examples/networks', 'src/test/data')"
    - cd src && pytest --cov=infomap --cov=branch --cov-report=term-missing:skip-covered --no-cov-on-fail {{ pytest_args }}

about:
  home: https://www.mapequation.org/infomap
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: dist/LICENSE
  summary: Infomap network clustering algorithm
  doc_url: https://mapequation.github.io/infomap/python

extra:
  recipe-maintainers:
    - bollwyvl
