{% set name = "python-infomap" %}
{% set pyname = "infomap" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pyname[0] }}/{{ pyname }}/{{ pyname }}-{{ version }}.tar.gz
  sha256: 84efdeea6cb3664edad563d0027548a93016b0abf5bef5dbdeea7e49a5493e86

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - infomap

about:
  home: https://www.mapequation.org/infomap
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE_AGPLv3.txt
  summary: Infomap is a network clustering algorithm based on the Map equation. Python package.
  doc_url: https://mapequation.github.io/infomap/python/

extra:
  recipe-maintainers:
    - TnTo
